steps:
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]

- name: python
  entrypoint: python
  args: ["test_app.py"] 

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/bmi', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/bmi']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'bmi-api', '--image=asia.gcr.io/$PROJECT_ID/bmi', '--region', 'asia-southeast2', '--platform', 'managed', '--allow-unauthenticated']

